### ISSUE TITLE
sql文のフォーマット修正、AUTO_INCREMENT=1についての認識合わせ

### ISSUE THREAD

**Issue by yoshi-koyama** [shinmyoun/spring_DateCalc#1]
# 概要
https://github.com/shinmyoun/spring_DateCalc/blob/d1fc2f5c8b105407b1260a14e5cbdbedbe780325/sql/001-create-table-and-data.sql#L3-L10
こちらですが、SQL文にフォーマットを掛けてください！

それから、`AUTO_INCREMENT = 1;`でauto_incrementをリセットしているのはどうしてでしょうか？
テーブルをDropしているので不要な気がします。

# 完了の定義
- [x] sql文がフォーマットされていること
- [x] AUTO_INCREMENT=1の必要性について検討していること
- [x] 修正対応のPRが作成されていること
- [x] PRがレビューされマージされていること

**Comment by shinmyoun** [comment]
SQL文にフォーマットを適用しました。

`AUTO_INCREMENT = 1;`でauto_incrementをリセットしているのは、理由はないです。
他の方の書き方を参考にした書き方をそのまま使ってました。
実装理由が説明できないのに使ったのは、よくないと思いました。
参考にするにしても説明できる前提で実装できるよう気を付けます。

**Comment by yoshi-koyama** [comment]
対応頂いたのでクローズ
