### ISSUE TITLE
不要なコメントを消す

### ISSUE THREAD

**Issue by yoshi-koyama** [shinmyoun/spring_DateCalc#2]
# 概要

https://github.com/shinmyoun/spring_DateCalc/blob/d1fc2f5c8b105407b1260a14e5cbdbedbe780325/src/main/java/com/example/api/config/SecurityConfig.java#L22-L32
こちらですが学習の途中なのであえてコメントアウトしているという気もしますが、
原則プロダクトコードには不要なコメントは残さないようにしてください。

コメントは原則、何をしているかは書かず、なぜそうしたのかといった意図がコードから読み取りづらい場合においてのみ書くとよいです。
（何をコメントに書くかは意見がわかれるところ）

# 完了の定義
- [x] コメントの要不要が検討されていること
- [x] 不要コメントは削除してPRをあげること
- [x] PRがレビューされマージされていること

**Comment by shinmyoun** [comment]
学習のため途中あえてコメントアウトしてます。
ただ、不要なコメントなので消します。

**Comment by yoshi-koyama** [comment]
対応頂いたのでクローズ
